extends Node

enum State {IDLE, MOVE, WALK, JUMP, FALL, DEAD, ATTACK, HURT, RELOADING, EXECUTE, CUTSCENE, DASH, EAT, SLEEP, PLAYER_ON_BEAK, HUNGRY, BLOCK, TRILL}

enum Facing {RIGHT,LEFT}
enum Looking {UP, FORWARD, DOWN}


