extends Node

signal player_changed_facing
signal player_attacked
signal player_executed
signal player_changed_state
signal player_health_changed
signal double_jump_refreshed
signal cutscene_started
signal cutscene_ended
