extends Node

signal player_changed_facing
signal player_attacked
signal player_executed
signal player_changed_state
signal player_health_changed
signal double_jump_refreshed
signal cutscene_started
signal cutscene_ended
signal added_food_to_bag
signal removed_food_from_bag
signal charge_amount_changed
signal enemy_took_damage
