extends Node



const LEVEL_MAP: Dictionary = {
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-1.tscn": "res://levels_and_level_objects/map/map_world_1.tscn",
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-2.tscn": "res://levels_and_level_objects/map/map_world_1.tscn",
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-3.tscn": "res://levels_and_level_objects/map/map_world_1.tscn",
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-4.tscn": "res://levels_and_level_objects/map/map_world_1.tscn",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-1.tscn": "res://levels_and_level_objects/map/map_world_2.tscn",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-2.tscn": "res://levels_and_level_objects/map/map_world_2.tscn",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-3.tscn": "res://levels_and_level_objects/map/map_world_2.tscn",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-4.tscn": "res://levels_and_level_objects/map/map_world_2.tscn",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-1.tscn": "res://levels_and_level_objects/map/map_world_3.tscn",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-2.tscn": "res://levels_and_level_objects/map/map_world_3.tscn",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-3.tscn": "res://levels_and_level_objects/map/map_world_3.tscn",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-4.tscn": "res://levels_and_level_objects/map/map_world_3.tscn",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-1.tscn": "res://levels_and_level_objects/map/map_world_4.tscn",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-2.tscn": "res://levels_and_level_objects/map/map_world_4.tscn",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-3.tscn": "res://levels_and_level_objects/map/map_world_4.tscn",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-4.tscn": "res://levels_and_level_objects/map/map_world_4.tscn",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-1.tscn": "res://levels_and_level_objects/map/map_world_5.tscn",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-2.tscn": "res://levels_and_level_objects/map/map_world_5.tscn",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-3.tscn": "res://levels_and_level_objects/map/map_world_5.tscn",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-4.tscn": "res://levels_and_level_objects/map/map_world_5.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-1.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-2.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-3.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-4.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-1.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-2.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-3.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-4.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-1.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-2.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-3.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-4.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
}

const WORLD_NAME: Dictionary = {
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-1.tscn": "Learnin'",
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-2.tscn": "Belts",
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-3.tscn": "Wet Behind the Ears",
	"res://levels_and_level_objects/level_scenes/world_1_levels/1-4.tscn": "The Captain",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-1.tscn": "Ah Don't Care fer Slime",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-2.tscn": "Bouncer",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-3.tscn": "Rotten Fish",
	"res://levels_and_level_objects/level_scenes/world_2_levels/2-4.tscn": "The Root of the Problem",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-1.tscn": "Fantastic",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-2.tscn": "Rust to Rust",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-3.tscn": "Living Pain",
	"res://levels_and_level_objects/level_scenes/world_3_levels/3-4.tscn": "Ol' Inky",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-1.tscn": "Give Yuh a Boost",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-2.tscn": "Stalagg-whatevers",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-3.tscn": "Hope These Don't Hatch",
	"res://levels_and_level_objects/level_scenes/world_4_levels/4-4.tscn": "The Wave",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-1.tscn": "They All Got Parasites",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-2.tscn": "Coal Chopper",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-3.tscn": "Keep Yer Feet Movin'",
	"res://levels_and_level_objects/level_scenes/world_5_levels/5-4.tscn": "Quiet 'Round Here",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-1.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-2.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-3.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_6_levels/6-4.tscn": "res://levels_and_level_objects/map/map_world_6.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-1.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-2.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-3.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_7_levels/7-4.tscn": "res://levels_and_level_objects/map/map_world_7.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-1.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-2.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-3.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
	"res://levels_and_level_objects/level_scenes/world_8_levels/8-4.tscn": "res://levels_and_level_objects/map/map_world_8.tscn",
}
